### ISSUE TITLE
Please update to Vue 2.0 and stuff

### ISSUE THREAD

**Issue by reisnobre** [GuillaumeLeclerc/vue-google-maps#119]
Only this bro,
Please, update <3

**Comment by xkjyeah** [comment]
Sorry for the self-plug, but try [vue2-google-maps](https://github.com/xkjyeah/vue-google-maps)

**Comment by GuillaumeLeclerc** [comment]
Would you want write access to merge it here ? , I have not tried vue2 yet.

**Comment by xkjyeah** [comment]
That would be good. Since your repository has all the stars the vue 2
version can now go on the CDN

**Comment by GuillaumeLeclerc** [comment]
Is your version backward compatible ?


Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Daniel Sim <notifications@github.com> Date : 08.01.17  14:44  (GMT+01:00) À : GuillaumeLeclerc/vue-google-maps <vue-google-maps@noreply.github.com> Cc : Guillaume Leclerc <guillaume.leclerc.work@gmail.com>, Comment <comment@noreply.github.com> Objet : Re: [GuillaumeLeclerc/vue-google-maps] Please update to Vue 2.0 and stuff (#119) 
That would be good. Since your repository has all the stars the vue 2

version can now go on the CDN



On 8 Jan 2017 4:25 p.m., "Guillaume Leclerc" <notifications@github.com>

wrote:

**Comment by xkjyeah** [comment]
Unfortunately, no. Vue 2 does not have two way binding or events, so it
involved quite an extensive rewrite

**Comment by reisnobre** [comment]
I end up using just a loader to expose the google object, but I'll look at your project @xkjyeah
