### ISSUE TITLE
Marker label doesn't work

### ISSUE THREAD

**Issue by xkjyeah** [GuillaumeLeclerc/vue-google-maps#25]
When I use label="1" , Vue says:

     Invalid prop: type check failed for label="'1' | makeMarkerLabel". Expected Object, got String.

When I use a filter (e.g. Vue.filter('makeMarkerLabel', x => new google.maps.MarkerLabel({text: x}))), Google API doesn't provide the marker label constructor

**Comment by GuillaumeLeclerc** [comment]
Indeed you are right the validator is not correct. 

On the other side the next error you point is absolutely normal since you don't wait the google maps api to be loaded. 

Before using anything in the google namespace you need to be sure it's loaded. You can get this information with the `loaded` promise.

**Comment by GuillaumeLeclerc** [comment]
Closed by #26
