### ISSUE TITLE
small issues when setting up markers & google map

### ISSUE THREAD

**Issue by FWSimon** [GuillaumeLeclerc/vue-google-maps#38]
Hi,

Thanks for a nice plugin.
I just have some problems setting it up.

this is my vue file (template) https://gist.github.com/FWSimon/8a7d154217082d3c3f19

and this is my HTML

```html
<center-overview inline-template>
<google-map style="height: 600px;" class=" col-xs-12" :center="{lat: 56.16744, lng: 11.36104}" :zoom="7"></google-map>
</center-overview>
```
I keep getting this error
`[Vue warn]: Prop "zoom" expects a two-way binding type.` and `[Vue warn]: Prop "center" expects a two-way binding type.`

And I don't know where to but the <marker>, I have tried to put it in the `<google-map></google-map>` component but didn't work.

Can I remove the `:center="{lat: 56.16744, lng: 11.36104}"` and use the center data i have from my .js file instead?

Hope someone can help me out :+1:

**Comment by smartpierre** [comment]
First of all, you should not put your Google Map API key in a public file.
Here is how you should use the map component :

`
<map :center.sync="map.center"
                 :zoom.sync="map.zoom"
                 :map-type-id.sync="map.mapType">
</map>
<script type="text/ecmascript-6">
export default {
        data() {
            return {
                map: {
                    center: { lat: 44.8456399, lng: -0.5735126 },
                    zoom: 11,
                    mapType: 'terrain'
                }
            }
        },

        components: {
            Map
        }
}
</script>
`

By adding '.sync' to the props you specify that the variable is synchronized with the components :

http://vuejs.org/guide/components.html#Prop-Binding-Types

**Comment by FWSimon** [comment]
ah thanks @smartpierre I'm still confused about the marker part, I have created a new component named marker 

```js
    components: {
        'Map': VueGoogleMap.Map,
        'Marker': VueGoogleMap.Marker
    },
```

but yea, i dont know how to get the marker on the map

**Comment by smartpierre** [comment]
I updated the gist for you : 

https://gist.github.com/smartpierre/ef58fe6c6635871bf7f8

If you have multiple markers in an array you can add : 

``v-for="marker in markers"``

to the <marker> component

**Comment by GuillaumeLeclerc** [comment]
@smartpierre is doing a great job here but I only want to point something about the `.sync` modifier.

In `vue`, `.sync` means that if the value of the child component changes then the parent will also update it's value. In this context that means for example if the user change the center of the map and you have `.sync` enabled then the new center will be written in what you have inside the center attribute. Basically `vue` will do the following thing: `{lat: 56.16744, lng: 11.36104}= the_new_center_after_the_user_changed_it`. but as you can guess this statement does not makes sense because the left hand side of the equality is constant, this is why you get an error.

On the other side if you don't want to update the values according to the user actions(which is what I suspect you want to do) then you can remove the `.sync`. In this case you will get a warning from `vue`. I don't get why but vue complains when you do not sync a value from a syncable property, I tried to remove this warning without success. This is perfectly fine to ignore this.

Please reopen if you have any additional questions
