### ISSUE TITLE
Loads all of lodash

### ISSUE THREAD

**Issue by rjoo** [GuillaumeLeclerc/vue-google-maps#55]
For a project that doesn't use lodash, this imports all of lodash adding an extra whopping 500kb to the unminified bundled file.

Even if minified/gzipped, it's still a ton of unused code.

I think a good way around this is to import lodash modules as they're needed.

````javascript
import forEach from 'lodash/forEach'

forEach()
````

Thoughts?

Looking through the code base, looks like there are only 7 unique lodash functions being used, which would save a ton on the file size.

**Comment by GuillaumeLeclerc** [comment]
Someone already suggested this in #44. My point was `vue-google-maps-example` build is about 200k, less than the lodash build. I assume webpack is already optimizing this. Can you explain me your build process to know how you can reach a build size that big ?

As I said in #44 By doing such optimizations the `vue-google-maps-example` build size increases by 30kb. 

Actually there is a better solution for this kind of problem. There is a webpack plugin that optimize lodash dependencies for you. I used it in my other plugin `vue-seo` with great results (the built version is less than 40kb). The only problem is doing what you suggest is basically "inlining" lodash calls inside the plugin itself. So it will reduce your build size but for other users (the ones who use lodash somewhere else), it will do the opposite because they will have duplicated lodash code. 

From there I think we have two options:

- We optimize lodash by "inlining" lodash calls. It can save up to 400kb for some users (the ones who don't bundle their code I assume). But will increase by 30kb for some others. To decide such a thing we must be sure the impact will be positive for most users (this is not the case for my company but I see I'm the only one I'm willing to do such a thing)
- I do a third build, a one "for users that don't already use lodash". The only problem I see is it might confuse users why there are so many different builds of `vue-google-maps` and we will have to make a tutorial "How to choose my build". 

Why do you think ?

**Comment by rjoo** [comment]
I was initially mistaken, sorry. I had some other dev modules using lodash@4 and completely skimmed over that this required lodash@3.10+. Webpack does indeed do a lot of optimizations with v3 but the end result is still a tad too big for me unfortunately. I'm prospecting this for a project already in prod.

I checked out the `optimizeLodash` branch and noticed a few components that weren't switched to the inline lodash calls. After making the switch, the build size for the `vue-google-maps-example` only went down from 230kb to ~211kb. Not much gains unfortunately. I'll definitely continue playing around with it though.

As for the options, I'm not entirely too sure. But with the realization of my mistake (and likely the same mistake in #44 ), I don't think a third build would be necessary.

**Comment by GuillaumeLeclerc** [comment]
The final version in v1 should not exceed 60kb. I hope it's good enough for you.
