### ISSUE TITLE
Detect when map is manually moved or zoomed

### ISSUE THREAD

**Issue by plarsson** [GuillaumeLeclerc/vue-google-maps#63]
Hi!

This is my attempt to explain (in more details) why I needed the zoom_event exposed as discussed in the pull event #59.

I have a use case where I need to detect if the map is moved or zoomed manually. With moved manually I mean a user initiated drag and with zoomed manually I mean a user initiated zoom via - + buttons or double click. In the end I would like to initiate a server side search when the map is moved or zoomed by the user.

It sounds like one could use the `bounds_changed` event and we're done! But... I'm also using the cluster function and it's using cluster.fitMapToMarkers() which causes a `bounds_changed` event.  

This could be handled by setting a state flag that a "programatic move" will be occurring before calling fitMapToMarkers(). So far ok... 

However another problem showed up and that's when a info window popup is not fitting on the map, the map will "scroll" and that causes a `bounds_changed` event.  I have no idea how to separate this from the user initiated `bounds_changed` event. 

My solution now is to use the `dragend` and `zoom_changed` event (patched in #59). Based on one of these events in combination with the "programatic move" flag above I will register that a user initiated move has occurred. This is stored as another state flag and then I execute the actual search on the `idle` event depending on this second flag. This works very well, but feels hackish. 

To get this to work I needed the zoom event to be exposed. I've been thinking on how to incapsulate this into vue-google-maps instead, possible as a new event or something, but so far I have not managed to fit it in.  

Any idea on how to solve this in any other way?

Thanks for a great component!

**Comment by GuillaumeLeclerc** [comment]
We had a similar goal when developing http://papayapods.com. However we thought it would not make sense to actually differentiate between programmatic moves and user moves because It would not be intuitive for the user.

Consider the following use case:

- The Info window is closed
- The info window is open
- The map moves to display the info window, depending on the info window size the map could move up to 100% of the height
- This was a programmatic move therefore no search is triggered on the server
- Nothing is displayed on the map
- The user drag the map by 1px
- Makers start appearing on the map

From a user point of view it looks like a bug. Don't you think so ?

**Comment by plarsson** [comment]
Yes, it makes sense! I'll do the same... will use the bounds change only. 
Thanks for the help
